- name: Cleanup - remove build dependencies
  apt:
    pkg:
      - rsync
      - ca-certificates
      - build-essential
      - postgresql-server-dev-{{ postgresql_major }}
      - curl
      - git
      - gpp
      - cpp
      - pkg-config
      - apt-transport-https
      - cmake
      - ninja-build
      - python-is-python2
      - zlib1g-dev
      - liblzo2-dev
      - libmsgpack-dev
      - libzmq3-dev
      - libevent-dev
      - libmecab-dev
      # - systemtap-sdt-dev
      # - ccache
      # - clang
      # from 08-plpgsql_check
      - libicu-dev
      # from pg_net & pgsql-http
      - libcurl4-openssl-dev
      # from pgsodium
      - libsodium-dev
    autoremove: true
    purge: true
    state: absent
