# pgsql-http
- name: pgsql-http - download latest release
  get_url:
    url: "https://github.com/pramsey/pgsql-http/archive/refs/tags/v{{ pgsql_http_release }}.tar.gz"
    dest: /tmp/pgsql_http-{{ pgsql_http_release }}.tar.gz
    checksum: "{{ pgsql_http_release_checksum }}"
    timeout: 60

- name: pgsql-http - unpack archive
  unarchive:
    remote_src: yes
    src: /tmp/pgsql_http-{{ pgsql_http_release }}.tar.gz
    dest: /tmp
  become: yes

- name: pgsql-http - build
  make:
    chdir: /tmp/pgsql-http-{{ pgsql_http_release }}
  become: yes

- name: pgsql-http - install
  make:
    chdir: /tmp/pgsql-http-{{ pgsql_http_release }}
    target: install
  become: yes
